# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: CycleChen
google_analytics: CycleChen
title: CycleChen

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: CycleChen

description: Stylish Jekyll Theme
author:
  me: /images/me.jpg
  name: CycleChen
  email: CycleChen@outlook.com
  github: cyclechen

  bio: Life is all of torture.
  
rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate